os: linux
dist: bionic   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - nightly
matrix:
  include:
    - os: osx
      language: shell
      osx_image: xcode11
# command to install dependencies
install:
  - pip install .
  - pip install codecov
  - pip install nose-cov
  - pip install nose-exclude
# command to run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then nosetests tests/test_spotify:LinuxTests --nocapture --with-cov --cov-config .coveragerc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then nosetests tests/test_spotify:DarwinTests --nocapture --with-cov --cov-config .coveragerc; fi
after_success:
- codecov
