os: linux
dist: bionic   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - nightly
matrix:
  include:
    - os: osx
      language: shell
      osx_image: xcode11
# command to install dependencies
install:
  - pip3 install --upgrade pip
  - pip3 install .
  - pip3 install -r dev-requirements.txt
# command to run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pytest --cov-config=.coveragerc --cov=SwSpotify tests/test_spotify.py::LinuxTests; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pytest --cov-config=.coveragerc --cov=SwSpotify tests/test_spotify.py::DarwinTests; fi
after_success:
- codecov
